f_num = int(input('Введите первое число: '))
s_num = int(input('Введите второе число: '))

print('Результаты арифметических операций:')
print('Сумма чисел:', f_num + s_num)
print('Разность чисел:', f_num - s_num)
print('Произведение чисел:', f_num * s_num)
print(f'Частное чисел: {f_num / s_num:.2f}')
print(f'Целочисленное деление чисел', f_num // s_num)
print('Остаток от деления чисел:', f_num % s_num)
print('Возведение первого числа в степень второго:', f_num ** s_num, '\n')

print('Результаты сравнений:')
print('Меньше:', f_num < s_num)
print('Меньше или равно:', f_num <= s_num)
print('Больше:', f_num > s_num)
print('Больше или равно:', f_num >= s_num)
print('Неравно:', f_num != s_num)
print('Равно:', f_num == s_num)